### ISSUE TITLE
make: *** [all] Error 2

### ISSUE THREAD

**Issue by manand881** [uav4geo/NodeCOLMAP#1]
tried to build it with docker but the build failed.
Makefile:102: recipe for target 'all' failed
the command '/bin/sh -c idconfig && mkdir build cd build && cmake .. && make -j$(nproc)' returned a non-zero code : 2

**Comment by pierotofy** [comment]
Hey @manand881 :hand: could you copy/paste the entire output from the build log?

**Comment by manand881** [comment]
forgive me for my inexperience. where can i find the build log? am i supposed to cut and post whats appearing on the terminal ?

**Comment by manand881** [comment]
Makefile:102: recipe for target 'all' failed
make: *** [all] Error 2
The command '/bin/sh -c ldconfig && mkdir build && cd build && cmake .. && make -j$(nproc)' returned a non-zero code: 2

**Comment by pierotofy** [comment]
Yep, just the output from the terminal (and the commands you typed).

**Comment by manand881** [comment]
So I typed these to begin with. 

`$ git clone https://github.com/uav4geo/NodeCM `
`$ cd NodeCM`
`$ docker build -t uav4geo/nodecm .`

I'm using windows 10 version 2004. AMD Ryzen 1500x

**Comment by pierotofy** [comment]
Oh, I see. There was a problem with an older version of mvs-texturing. I've pushed a fix already https://github.com/uav4geo/NodeCM/commit/ac7e518ca3ba7c132e045cb5a04afaf3015fea1d if you update and try to rebuild it should work.

Thanks for the report!

**Comment by manand881** [comment]
so i tried testing out the new fix you sent. it still doesn't work. only this time the terminal closes on its on and i don't see any docker containers on my dashboard that belong to NodeCM which were originally created after the execution of 

`docker build -t uav4geo/nodecm .`

it would be useful if you could write the errors and warnings to a log file in the same directory. i would be able to post the file here for your reference. 
i see a lot of warnings while building NodeCM
